### ISSUE TITLE
Relocation code also modifies relative paths if variables are used

### ISSUE THREAD

**Issue by olifre** [cvmfs/cvmfsexec#33]
While essentially harmless, this irritated me for a while — we set:
```
CVMFS_CACHE_BASE="${CACHEBASE_CVMFS}/cvmfscache"
```
in our configuration, and set the `CACHEBASE_CVMFS` dynamically before launching `cvmfsexec`. However, the actual cache ends up below that directory. In the temporarily created configuration, I find:
```
CVMFS_CACHE_BASE="${CACHEBASE_CVMFS}/absolute_path_to_cvmfsexec/.cvmfsexec/dist/cvmfscache"
```
This seems to be caused by the pattern matching in the relocation code
https://github.com/cvmfs/cvmfsexec/blob/683523a3441c647f9f653a6517439f78728086ec/mountrepo#L72-L75
which also picks up the `/cvmfscache` part of the path shown above. Using `${CACHEBASE_CVMFS}/cache_cvmfs` instead, this can be avoided. 

I sadly don't have a good proposal for a more robus regexp not breaking other cases.

**Comment by DrDaveD** [comment]
I suppose it instead of the one 
```
"s,^\([^/]*\)/cvmfs,\1$DIST/cvmfs," \
```
It could have both
```
"s,^\([^/]*\)/cvmfs$,\1$DIST/cvmfs," \
"s,^\([^/]*\)/cvmfs/,\1$DIST/cvmfs/," \
```
Do you want to try it?

**Comment by olifre** [comment]
That indeed seems to work as expected :+1: , and I don't see any adverse side-effects. Thanks!

**Comment by DrDaveD** [comment]
Alright I put that in the master branch but didn't tag another release yet.  Let me know if you need that.

**Comment by olifre** [comment]
Many thanks! 
Certainly not needed, we will now stay with `cache_cvmfs` in our setup at least until the next major update, just reported this so we can prevent others from falling into this trap.

**Comment by DrDaveD** [comment]
This went into 4.12.
