### ISSUE TITLE
When running on a Mac it fils but exit code is 0

### ISSUE THREAD

**Issue by mambelli** [cvmfs/cvmfsexec#64]
I ended up running (download and invoke in a unit test)  cvmfsexec on a Mac (intel Mac ) and the following happens:
```
/tmp/test1//cvmfsexec/cvmfsexec.tmp/latest/cvmfsexec -v
/tmp/test1//cvmfsexec/cvmfsexec.tmp/latest/cvmfsexec: line 55: exec: {STDINCOPYFD}: not found
```
There is no output on stdout, there is an error and the exit code ($? checked after execution) is 0

I know the Mac is not supported, but was expecting exit code 1

**Comment by DrDaveD** [comment]
Fixed in #65, although I didn't cut a new release with it yet.
