### ISSUE TITLE
Error from the example run of singcvmfs

### ISSUE THREAD

**Issue by sujeong-lee** [cvmfs/cvmfsexec#74]
Hi, thanks for making this amazing tool! 
I would like to use singcvmfs to mount cvmfs repositories in a pre-built centOS 7.9-based singularity image. 
It seemed that the example in readme.md was very close to what I wanted to do, so I simply followed it. 

I built the package using `./makedist -s default`
and then I got an error below:
```
$ ./singcvmfs -s exec -cip docker://centos:7 bash
Singularity> ls /cvmfs/atlas.cern.ch
ls: cannot access /cvmfs/atlas.cern.ch: Transport endpoint is not connected
```
and in logfile:
```
/usr/bin/cvmfs2: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/bin/cvmfs2)
/usr/bin/cvmfs2: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/cvmfs2)
```

But when I tried with Centos 8 (docker://centos:8), it ran smoothly. 
Is singcvmfs not compatible with centOS 7 anymore?

Thanks!

**Comment by DrDaveD** [comment]
That looks like a case of the first "Caveat" in the singcvmfs section.

**Comment by DrDaveD** [comment]
I updated the README to suggest changing the example container to match the host operating system.
