### ISSUE TITLE
cvmfsexec for ubuntu

### ISSUE THREAD

**Issue by stebo85** [cvmfs/cvmfsexec#75]
Dear cvmfexec team,

I would like to run the cvmfs client on code ocean. But, code ocean does not allow fuse mounts for security reasons, so the standard ubuntu cvmfs package doesn't work. I was wondering if cvmfsexec would work, but makedist currently does not support ubuntu. Would it be possible to build this under ubuntu and could this then work on code coean?

Thank you for any hints
Steffen

**Comment by DrDaveD** [comment]
Hi Steffen,

It would require some effort but in principle it should work if makedist were updated to support ubuntu.  Are there any container systems available on that machine to unprivileged users, such as singularity or apptainer?  That might be easier to adapt.

However, I'm concerned about what you mean by not allowing fuse mounts.  Does it just mean that the fuse or fuse3 package is not installed?  Or have they done something else such as change the default permissions on /dev/fuse to not be usable by unprivileged users?  cvmfs will work without the fuse package but it needs /dev/fuse.  If the system admins have also disabled unprivileged user namespaces, that's going to be another hurdle.  You can easily test that by checking if `unshare -r true` succeeds.

Dave

**Comment by stebo85** [comment]
Dear @DrDaveD,

Thank you for the quick and very helpful answer! I tested a few more things and it seems there is very little luck to get cvmfs to work:

1)  `unshare -r true` results in `unshare: unshare failed: Operation not permitted`
2) apptainer/singularity can be installed, but a shell in a container leads to:
```
INFO   : A system administrator may need to enable user namespaces, install
INFO   :   apptainer-suid, or compile with ./mconfig --with-suid
ERROR  : Failed to create user namespace: user namespace requires to set /proc/sys/kernel/unprivileged_userns_clone to 1
```

and 
```
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while preparing image: while handling image.simg: while extracting image: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace requires to set /proc/sys/kernel/unprivileged_userns_clone to 1
: exit status 1
```

3) /dev/fuse is not available and I asked the support about it and they said they disabled this for security reasons

Looks like it's not possible or do you have any other idea?

**Comment by DrDaveD** [comment]
I am afraid you are out of options on that machine, sorry.

**Comment by stebo85** [comment]
thank you for confirming :)
