### ISSUE TITLE
Running cvmfsexec requires an unprivileged installation for singularity?

### ISSUE THREAD

**Issue by sujeong-lee** [cvmfs/cvmfsexec#80]
Hi, I would like to use cvmfsexec to load singularity images stored in a cvmfs server. 
So I mounted my cvmfs server first, checked I was able to access the saved singularity image, and then ran the image. 
But I got a weird singularity error. 

I found this error always happens when one tries to run a singularity image when cvmfs repos are being mounted by cvmfsexec. 
This error is not limited to a specific singularity image or repository. 
I was able to reproduce the error with one of the example repositories and a couple of simple singularity images that are not even in the repository. 

Here is what I did to reproduce the error: 

First I made sure my singularity image run smoothly. This image is NOT in a cvmfs repository.  
```
$ singularity run lolcow_latest.sif 
 _________________________________________
/ Persons attempting to find a motive in  \
| this narrative will be prosecuted;      |
| persons attempting to find a moral in   |
| it will be banished; persons attempting |
| to find a plot in it will be shot. By   |
| Order of the Author                     |
|                                         |
| -- Mark Twain, "The Adventures of       |
\ Huckleberry Finn"                       /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
And then I mounted a cvmfs repository as below, and run the same singularity image.  

```
$ cvmfsexec grid.cern.ch --
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /projects/fiat.lux/sjlee/workspace/euclid-repos/cvmfsexec-4.33/tmp/.cvmfsexec/dist/cvmfs/cvmfs-config.cern.ch
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /projects/fiat.lux/sjlee/workspace/euclid-repos/cvmfsexec-4.33/tmp/.cvmfsexec/dist/cvmfs/grid.cern.ch
$ singularity run lolcow_latest.sif 
INFO:    Convert SIF file to sandbox...
ERROR  : No setuid installation found, for unprivileged installation use: ./mconfig --without-suid
```

Could you help me to figure out why this is happening? I am working on a computer cluster at my institution which is RedHat 8.0, and the singularity version installed is v3.6. Singularity is globally installed.

**Comment by DrDaveD** [comment]
cvmfsexec uses unprivileged user namespaces, so setuid-root is not allowed.

You could instead run singularity from cvmfs.  I maintain it in oasis.opensciencegrid.org:
```
$ cvmfsexec oasis.opensciencegrid.org grid.cern.ch --
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /scratch/tmp/cvmfsexec/dist/cvmfs/config-osg.opensciencegrid.org
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /scratch/tmp/cvmfsexec/dist/cvmfs/oasis.opensciencegrid.org
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /scratch/tmp/cvmfsexec/dist/cvmfs/grid.cern.ch
$ PATH=/cvmfs/oasis.opensciencegrid.org/mis/apptainer/bin:$PATH
$ singularity --version
apptainer version 1.1.8-1.el7
```

**Comment by DrDaveD** [comment]
Alternatively, you could use `singularity run -u` to have your singularity version run unprivileged.

**Comment by DrDaveD** [comment]
> Alternatively, you could use `singularity run -u` to have your singularity version run unprivileged.

Oh but unless it has been upgradded to apptainer-1.1.0 or later, it won't be able to mount a .sif.  It will most likely be able to run a sandbox.
