### ISSUE TITLE
Setting `CVMFS_QUOTA_LIMIT` cauises I/O errors when CVMFS mounts are subsequently bind-mounted into apptainer

### ISSUE THREAD

**Issue by olifre** [cvmfs/cvmfsexec#90]
I am not at all sure `cvmfsexec` is at fault, this may be a problem in CVMFS itself... 

See the following reproducer on AlmaLinux 9:
```
$ wget https://github.com/cvmfs/cvmfsexec/archive/refs/tags/v4.39.tar.gz
$ tar xf v4.39.tar.gz
$ cd cvmfsexec-4.39/
$ ./mkaedist default
$ echo "CVMFS_QUOTA_LIMIT='1000'" >> dist/etc/cvmfs/default.local
$ ./makedist -o mcrun
$ ./mcrun atlas.cern.ch -- /bin/bash
...
(this shell is inside mcrun) $ ls /cvmfs/atlas.cern.ch/repo/sw/software/24.0/Athena/24.0.6
InstallArea
(this shell is inside mcrun) $ /cvmfs/atlas.cern.ch/repo/containers/sw/apptainer/x86_64-el7/1.2.2/bin/apptainer exec  --underlay -c -i -e   -B /cvmfs:/cvmfs /cvmfs/atlas.cern.ch/repo/containers/fs/singularity/x86_64-almalinux9 /bin/bash
...
(this shell is inside mcrun and apptainer) Apptainer> ls /cvmfs/atlas.cern.ch/repo/sw/software/24.0/Athena/24.0.5
ls: cannot open directory '/cvmfs/atlas.cern.ch/repo/sw/software/24.0/Athena/24.0.5': Input/output error
```

In short:
* Without the Apptainer layer at the end, CVMFS access works fine. 
* Without setting `CVMFS_QUOTA_LIMIT`, CVMFS access works fine also inside Apptainer. 

It seems to be the combination which breaks — as if the cache manager was having a problem. 

Exiting the container again and investigating the logs, I find:
```
$ cat .cvmfsexec/log/atlas.cern.ch.log
...
Mon Jun  3 22:15:36 2024 (atlas.cern.ch) released nested catalogs
Mon Jun  3 22:15:50 2024 (atlas.cern.ch) EIO (03) on /repo/sw/software/24.0/Athena/24.0.5
Mon Jun  3 22:15:50 2024 (atlas.cern.ch) released nested catalogs
```
which does not seem to be very enlightening.

**Comment by DrDaveD** [comment]
I think you probably just set a quota limit that's too small to work correctly with atlas.cern.ch.  The default value is 4000.  It
It's pretty common for the default cvmfs log to not be very enlightening. You could find out more details of the error by setting CVMFS_DEBUGLOG to point to a file.

**Comment by olifre** [comment]
It seems you are right — ­many thanks for the pointer!
The debug log confirms it:
```
(cache) commit failed: cannot pin 5739c7af41af5ddf18b761467cb41a0b555e90bf    [06-04-2024 02:16:51 CEST]
(catalog) failed to load catalog '/repo/sw/software/24.0/Athena/24.0.4' (2 - not enough space to load catalog)    [06-04-2024 02:16:51 CEST]
(cvmfs) EIO (03) on /repo/sw/software/24.0/Athena/24.0.4    [06-04-2024 02:16:51 CEST]
```
I would not have assumed this to happen, but assumed that the cache size must only be larger than the largest catalogue (even though this would mean a lot of eviction, of course, which would be fine in that case), but checking on the cache usage and docs, it seems this can happen (cache was slightly over 50 % filled, eviction did not happen yet, and the catalog did not fit in anymore). 

I can confirm that using a higher `CVMFS_QUOTA_LIMIT` fully fixes the issue. Thanks again, I would not have thought about this explanation!
