### ISSUE TITLE
FNAL mirror disappeared, breaking makedist on Centos7 

### ISSUE THREAD

**Issue by vvolkl** [cvmfs/cvmfsexec#91]
Running makedist on Centos7 gives 
```
No fuse-libs package found from https://linux-mirrors.fnal.gov/linux/centos/7/os/x86_64/Packages
```
and indeed that URL is no longer being served. Although we're beyond the EOL I think it makes sense to support Centos7 for a while longer, maybe until the end of the year.

I've checked, and fuse-libs can still be installed from https://vault.centos.org/centos/7/os/x86_64/Packages/ , although a straight-up replacement does not work, as the `latesturl` func seems to have an issue with that, I'll need to take a closer look.

In the meantime, a workaround is to hardcode the package url like this: 
```diff
--- a/makedist
+++ b/makedist

@@ -334,7 +334,8 @@ else
             URLS="$URLS $CVMFSFUSE3URL"
         fi
     fi
-    URL="`latesturl $FUSEURL $FUSELIB $FUSESUBDIR`"
+    #URL="`latesturl $FUSEURL $FUSELIB $FUSESUBDIR`"
+    URL="https://vault.centos.org/centos/7/os/x86_64/Packages/fuse-libs-2.9.2-11.el7.x86_64.rpm"
     if [ -z "$URL" ]; then
         echo "No $FUSELIB package found from $FUSEURL" >&2
         exit 1
```

**Comment by DrDaveD** [comment]
Thanks for the report.  Fixed in 4.40
